#!/usr/bin/env bash
# Nightly wiki lint — the job the docs have been claiming exists since May.
#
# Runs `wiki-ingest --operation lint --scope all`, then commits and pushes ONLY
# the audit artifacts it produced. Scheduled by
# ~/Library/LaunchAgents/com.nickdnj.wiki-lint.plist (3:17am local).
#
# Why this commits when wiki-ingest deliberately does not: wiki-ingest's
# no-auto-commit rule protects *curated pages*, which need Nick's review. Lint
# reports are additive, dated, generated audit artifacts under _lint/ — they
# conflict with nothing, and leaving them uncommitted every night would drop an
# unexplained dirty file into whatever session opens the wiki next.
#
# Only ever stages _lint/<date>.md and _changelog/<date>.md. Never `git add -A`
# — other agents and Nick's Obsidian session write to this repo too.
#
# Manual run:  bash scripts/nightly-wiki-lint.sh
# Logs:        ~/Library/Logs/wiki-lint.log

set -uo pipefail

export PATH="/opt/homebrew/bin:/Users/nickd/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIKI="${WIKI_REPO:-$HOME/Workspaces/wiki}"
TODAY="$(date +%F)"
LOG="$HOME/Library/Logs/wiki-lint.log"

mkdir -p "$(dirname "$LOG")"
exec >> "$LOG" 2>&1
echo "=============================================================="
echo "$(date '+%F %T') — nightly wiki lint starting"

if [[ ! -d "$WIKI/.git" ]]; then
  echo "ABORT: no wiki at $WIKI"
  exit 1
fi

# Refresh first so the lint sees current content. Never force, never rebase over
# someone's uncommitted work — if it won't fast-forward, lint what we have and
# say so.
if ! git -C "$WIKI" pull --ff-only --quiet 2>&1; then
  echo "WARN: could not fast-forward the wiki; linting the current checkout as-is"
fi

cd "$REPO_ROOT"
if ! WIKI_REPO="$WIKI" node scripts/run-agent.js wiki-ingest --operation lint --scope all; then
  echo "ERROR: lint run failed (exit $?)"
  exit 1
fi

# Commit only what this run produced.
staged=0
for f in "_lint/$TODAY.md" "_changelog/$TODAY.md"; do
  if [[ -e "$WIKI/$f" ]] && ! git -C "$WIKI" diff --quiet --exit-code -- "$f" 2>/dev/null; then
    git -C "$WIKI" add -- "$f" && staged=1
  elif [[ -e "$WIKI/$f" ]] && git -C "$WIKI" ls-files --error-unmatch -- "$f" >/dev/null 2>&1; then
    : # tracked and unchanged
  elif [[ -e "$WIKI/$f" ]]; then
    git -C "$WIKI" add -- "$f" && staged=1   # new untracked artifact
  fi
done

if [[ "$staged" -eq 1 ]]; then
  git -C "$WIKI" commit -q -m "wiki lint: $TODAY (automated nightly)

Generated by scripts/nightly-wiki-lint.sh via launchd.
Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"
  if git -C "$WIKI" push -q; then
    echo "$(date '+%F %T') — lint committed and pushed: $(git -C "$WIKI" rev-parse --short HEAD)"
  else
    echo "$(date '+%F %T') — lint committed locally; push failed (offline?)"
  fi
else
  echo "$(date '+%F %T') — lint produced no new artifacts; nothing committed"
fi

echo "$(date '+%F %T') — done"
